export enum AttendanceStatus {
  PENDIENTE = 'PENDIENTE',
  PRESENTE = 'PRESENTE',
  FINALIZADO = 'FINALIZADO',
  FALTA_JUSTIFICADA = 'FALTA_JUSTIFICADA',
  FALTA_INJUSTIFICADA = 'FALTA_INJUSTIFICADA',
  SALIDA_ANTICIPADA = 'SALIDA_ANTICIPADA',
  ANULADO = 'ANULADO',
}

export enum RegisterType {
  AUTOMATICO = 'AUTOMATICO',
  MANUAL = 'MANUAL',
}

export enum GeoStatus {
  DENTRO_ZONA = 'DENTRO_ZONA',
  FUERA_ZONA = 'FUERA_ZONA',
  NO_DISPONIBLE = 'NO_DISPONIBLE',
}

export enum GeoEventType {
  ENTRADA = 'ENTRADA',
  SALIDA = 'SALIDA',
  MODIFICACION = 'MODIFICACION',
  ANULACION = 'ANULACION',
}

export enum JustificationType {
  FALTA = 'FALTA',
  SALIDA_ANTICIPADA = 'SALIDA_ANTICIPADA',
  OTRA = 'OTRA',
}

export enum JustificationStatus {
  PENDIENTE = 'PENDIENTE',
  APROBADA = 'APROBADA',
  RECHAZADA = 'RECHAZADA',
}
