/** Codigos exactos registrados en la tabla roles */
export enum RoleCode {
  ADMIN = 'ADMIN_SISTEMA',
  JEFE_INSTRUCCION = 'JEFE_INSTRUCCION',
  SUBJEFE_INSTRUCCION = 'SUBJEFE_INSTRUCCION',
  ADJUNTO_INSTRUCCION = 'ADJUNTO_INSTRUCCION',
  ENCARGADO_GRUPO = 'ENCARGADO_GRUPO',
}
